### ISSUE TITLE
Add a license for world_builder

### ISSUE THREAD

**Issue by MrRar** [Skamiz/world_builder#1]
I might want to borrow some parts of this mod in the future for edit mod like the paste preview entity rotation table. To do that this mod needs a proper license.

BTW I couldn't figure out how to copy and paste. The tool tip for the clipboard says you can press Ctrl+LMB. I tried this and also pressing E+LMB but it did nothing. I don't think mods can even detect the Ctrl key. I had an area selected while trying to use the clipboard.

**Comment by Skamiz** [comment]
It is bound to the aux1 key, I completely forgot that it isn't on Ctrl by default. But when I change it back to E I have no issue copying by E + Ctrl. Dunno what the issue is there.
This is quite annoying since I feel like putting 'aux1' into the description isn't going to be very clear.  But probably the only option, since Minetest is unlikely to tell me the users keybind settings any time soon.

But I am already planing to make all the functions explicitly accessible through the formspec to mitigate this kind of issue, which will leave the key combos only as a handy shortcut rather then a necessity.

The lack of license is kind of intentional, since this isn't really published yet, but I intend to release it as MIT once I get around to it. It's just that the attitude on certain people on the forum seriously burned me out on wanting to deal with anything license related. >.<
For now you have my blessing to treat it as if it's already MIT if you are willing to take my word for it. Take whatever you need, since your own mod was a huge inspiration for this one.

**Comment by Skamiz** [comment]
Turns out I **can** find out custom keybinds simply through the settings object, just like any other setting. I would just need to translate things like 'KEY_LCONTROL' to 'Ctrl' to make it readable, and it wouldn't work in multiplayer, so for now this goes on the TODO list.

**Comment by MrRar** [comment]
I'm not sure what I was doing wrong the last time but now that I tried it again with LMB+E it did work.

It looks like your implementation is also using hollowing of the paste preview so that is pretty cool.

Thanks for licensing this. I might want to adapt a few things like I said. I would have to change the license of edit to MIT. That's OK since it is CC0 now.

**Comment by Skamiz** [comment]
Just added license explicitly to the project.

Also fixed the bug where the hollowing was modifying the original schematic, not only the preview.

The though behind the hollowing is that, since there is a limited number of nodes I can display, I want to display ones that are important for placing the schematic, and thus nodes which are surrounded from all sides aren't really needed for that.
The next step would be to get rid of nodes which are exposed to air, but have no direct path towards the selections bounding box, like internal walls and such.
